server:
  port: 8084

spring:
  application:
    name: API-GATEWAY
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**,/staffs/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**


jwt:
   secret: afafasfafafasfasfasfafacasdasfasxASFACASDFACASDFASFASFDAFASFASDAADSCSDFADCVSGCFVADXCcadwavfsfarvf


#okta configuration for api gateway
#
#okta:
#  oauth2:
#    issuer: https://dev-00832855.okta.com/oauth2/default
#    audience: api://default
#    client-id: 0oaf5vh8ulL3jWkID5d7
#    client-secret: L3AYa_g2ibL_8lI5QlRq_KHKiLAJO_aSuUuLd_2Eucgm9tvkf30LXrhlJn6dERid
#    scopes: openid, profile, email, offline_access