server:
  port: 8084

spring:
  application:
    name: API-GATEWAY
    
  config:
    import: optional:configserver:http://localhost:8085    
  profiles:
    active: dev
    
jwt:
   secret: afafasfafafasfasfasfafacasdasfasxASFACASDFACASDFASFASFDAFASFASDAADSCSDFADCVSGCFVADXCcadwavfsfarvf
